### ISSUE TITLE
ImportError: HDFStore requires PyTables, "No module named tables" problem importing

### ISSUE THREAD

**Issue by zirohut** [BVLC/caffe#1462]
```
GPU mode
Loading input...
Processed 178 windows in 4.082 s.
Traceback (most recent call last):
  File "python/detect.py", line 174, in <module>
    main(sys.argv)
  File "python/detect.py", line 167, in main
    df.to_hdf(args.output_file, 'df', mode='w')
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.15.0-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 896, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.15.0-py2.7-linux-x86_64.egg/pandas/io/pytables.py", line 293, in to_hdf
    complib=complib) as store:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.15.0-py2.7-linux-x86_64.egg/pandas/io/pytables.py", line 274, in get_store
    store = HDFStore(path, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.15.0-py2.7-linux-x86_64.egg/pandas/io/pytables.py", line 412, in __init__
    raise ImportError('HDFStore requires PyTables, "{ex}" problem importing'.format(ex=str(ex)))
ImportError: HDFStore requires PyTables, "No module named tables" problem importing
```

**Comment by dm02** [comment]
Hi,
How did you fix the above mentioned problem?
