### ISSUE TITLE
Non-existent IMAGE_DATA source file causes segmentation fault in caffe::ImageDataLayer<float>::DataLayerSetUp

### ISSUE THREAD

**Issue by michaelbrundage** [BVLC/caffe#1602]
I copied the solver.prototxt and train_val.prototxt files from models/bvlc_reference_caffenet, modified the latter to use IMAGE_DATA layers, and then attempted to run caffe, but my train.prototxt contained an error -- the source file specified (file_list.txt) did not exist. It crashes with an uncaught segfault instead of properly reporting the error. The only hint was the "A total of 0 images." message.

Below are machine details, gdb backtrace, and command and log output:

Machine: MacBook Pro Retina Late 2013, Mac OS X 10.10.1, 16GB RAM

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000100074fbd in caffe::ImageDataLayer<float>::DataLayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) ()
(gdb) bt
#0  0x0000000100074fbd in caffe::ImageDataLayer<float>::DataLayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) ()
#1  0x000000010005979e in caffe::BaseDataLayer<float>::LayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) ()
#2  0x000000010005aede in caffe::BasePrefetchingDataLayer<float>::LayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) ()
#3  0x00000001000964fe in caffe::Net<float>::Init(caffe::NetParameter const&) ()
#4  0x000000010009578b in caffe::Net<float>::Net(caffe::NetParameter const&) ()
#5  0x00000001000ac4e8 in caffe::Solver<float>::InitTrainNet() ()
#6  0x00000001000abf4f in caffe::Solver<float>::Init(caffe::SolverParameter const&) ()
#7  0x00000001000abdfc in caffe::Solver<float>::Solver(caffe::SolverParameter const&) ()
#8  0x0000000100003e60 in caffe::Solver<float>* caffe::GetSolver<float>(caffe::SolverParameter const&) ()
#9  0x000000010000183e in train() ()
#10 0x0000000100003871 in main ()
```

```
> caffe train --solver=solver.prototxt --snapshot=train_10000.solverstate
I1219 23:05:39.339426 2052915968 caffe.cpp:103] Use CPU.
I1219 23:05:39.340448 2052915968 caffe.cpp:107] Starting Optimization
I1219 23:05:39.340461 2052915968 solver.cpp:32] Initializing solver from parameters: 
test_iter: 1000
test_interval: 1000
base_lr: 0.01
display: 20
max_iter: 450000
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 100000
snapshot: 10000
snapshot_prefix: "train_snap"
solver_mode: CPU
net: "train.prototxt"
I1219 23:05:39.340579 2052915968 solver.cpp:67] Creating training net from net file: train.prototxt
I1219 23:05:39.342327 2052915968 net.cpp:275] The NetState phase (0) differed from the phase (1) specified by a rule in layer data
I1219 23:05:39.342564 2052915968 net.cpp:275] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy
I1219 23:05:39.342572 2052915968 net.cpp:39] Initializing net from parameters: 
name: "NationalDataScienceBowl"
layers {
  top: "data"
  top: "label"
  name: "data"
  type: IMAGE_DATA
  image_data_param {
    source: "file_list.txt"
    batch_size: 50
    new_height: 64
    new_width: 64
  }
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: true
    crop_size: 60
    mean_file: "average.png"
  }
}
layers {
  bottom: "data"
  top: "conv1"
  name: "conv1"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layers {
  bottom: "conv1"
  top: "conv1"
  name: "relu1"
  type: RELU
}
layers {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layers {
  bottom: "pool1"
  top: "norm1"
  name: "norm1"
  type: LRN
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layers {
  bottom: "norm1"
  top: "conv2"
  name: "conv2"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 256
    pad: 2
    kernel_size: 5
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layers {
  bottom: "conv2"
  top: "conv2"
  name: "relu2"
  type: RELU
}
layers {
  bottom: "conv2"
  top: "pool2"
  name: "pool2"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layers {
  bottom: "pool2"
  top: "norm2"
  name: "norm2"
  type: LRN
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layers {
  bottom: "norm2"
  top: "conv3"
  name: "conv3"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layers {
  bottom: "conv3"
  top: "conv3"
  name: "relu3"
  type: RELU
}
layers {
  bottom: "conv3"
  top: "conv4"
  name: "conv4"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layers {
  bottom: "conv4"
  top: "conv4"
  name: "relu4"
  type: RELU
}
layers {
  bottom: "conv4"
  top: "conv5"
  name: "conv5"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layers {
  bottom: "conv5"
  top: "conv5"
  name: "relu5"
  type: RELU
}
layers {
  bottom: "conv5"
  top: "pool5"
  name: "pool5"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layers {
  bottom: "pool5"
  top: "fc6"
  name: "fc6"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  inner_product_param {
    num_output: 4096
    weight_filler {
      type: "gaussian"
      std: 0.005
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layers {
  bottom: "fc6"
  top: "fc6"
  name: "relu6"
  type: RELU
}
layers {
  bottom: "fc6"
  top: "fc6"
  name: "drop6"
  type: DROPOUT
  dropout_param {
    dropout_ratio: 0.5
  }
}
layers {
  bottom: "fc6"
  top: "fc7"
  name: "fc7"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  inner_product_param {
    num_output: 4096
    weight_filler {
      type: "gaussian"
      std: 0.005
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layers {
  bottom: "fc7"
  top: "fc7"
  name: "relu7"
  type: RELU
}
layers {
  bottom: "fc7"
  top: "fc7"
  name: "drop7"
  type: DROPOUT
  dropout_param {
    dropout_ratio: 0.5
  }
}
layers {
  bottom: "fc7"
  top: "fc8"
  name: "fc8"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  inner_product_param {
    num_output: 1000
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layers {
  bottom: "fc8"
  bottom: "label"
  top: "loss"
  name: "loss"
  type: SOFTMAX_LOSS
}
state {
  phase: TRAIN
}
I1219 23:05:39.343217 2052915968 net.cpp:67] Creating Layer data
I1219 23:05:39.343228 2052915968 net.cpp:356] data -> data
I1219 23:05:39.343250 2052915968 net.cpp:356] data -> label
I1219 23:05:39.343260 2052915968 net.cpp:96] Setting up data
I1219 23:05:39.343267 2052915968 image_data_layer.cpp:30] Opening file file_list.txt
I1219 23:05:39.343286 2052915968 image_data_layer.cpp:45] A total of 0 images.
zsh: segmentation fault  caffe train --solver=solver.prototxt --snapshot=train_10000.solverstate
```

**Comment by shelhamer** [comment]
Fixed in #1551.
