### ISSUE TITLE
Caffe prediction grayscale images - index out of range error

### ISSUE THREAD

**Issue by olddocks** [BVLC/caffe#1808]
i am trying to do multi label regression of 96 pixel grayscale images. i successfully trained the model and when i predict i get this weird error
```
  File "output.py", line 19, in <module>
    net = caffe.Classifier(MODEL_FILE, PRETRAINED)
  File "/home/pbu/Desktop/caffe/python/caffe/classifier.py", line 43, in __init__
    self.crop_dims = np.array(self.blobs[self.inputs[0]].data.shape[2:])
IndexError: list index out of range
```

My python script is simple
```
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd


import caffe

# Set the right path to your model definition file, pretrained model weights,
# and the image you would like to classify.
MODEL_FILE = './facialkp.prototxt'
PRETRAINED = './tmp_iter_1000_1.94e.caffemodel'


net = caffe.Classifier(MODEL_FILE, PRETRAINED)
			
caffe.set_phase_test()
caffe.set_mode_cpu()

df = pd.read_csv('test.csv',header=0)

df['Image'] = df['Image'].apply(lambda im: np.fromstring(im, sep=' ') )
X = np.vstack (df['Image'].values) / 255 
X = X.astype(np.float32)
X = X.reshape((-1,1,96,96))


for k in xrange(10):
 input = caffe.io.load_image(X[k], color=False)
 prediction = net.predict([input]) 
 print 'Predicted:', prediction
```

The full output of layers
```
pbu@pbu-OptiPlex-740-Enhanced:~/Desktop$ python output.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0128 18:18:13.018959  3892 net.cpp:275] The NetState phase (0) differed from the phase (1) specified by a rule in layer data
I0128 18:18:13.019235  3892 net.cpp:39] Initializing net from parameters: 
name: "FKPReg"
layers {
  top: "data"
  top: "label"
  name: "fkp"
  type: HDF5_DATA
  hdf5_data_param {
    source: "train.txt"
    batch_size: 100
  }
  include {
    phase: TRAIN
  }
}
layers {
  bottom: "data"
  top: "conv1"
  name: "conv1"
  type: CONVOLUTION
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
  }
}
layers {
  bottom: "conv1"
  top: "conv1"
  name: "relu1"
  type: RELU
}
layers {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layers {
  bottom: "pool1"
  top: "norm1"
  name: "norm1"
  type: LRN
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layers {
  bottom: "norm1"
  top: "conv2"
  name: "conv2"
  type: CONVOLUTION
  convolution_param {
    num_output: 256
    pad: 2
    kernel_size: 5
    group: 2
  }
}
layers {
  bottom: "conv2"
  top: "conv2"
  name: "relu2"
  type: RELU
}
layers {
  bottom: "conv2"
  top: "pool2"
  name: "pool2"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layers {
  bottom: "pool2"
  top: "norm2"
  name: "norm2"
  type: LRN
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layers {
  bottom: "norm2"
  top: "conv3"
  name: "conv3"
  type: CONVOLUTION
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
  }
}
layers {
  bottom: "conv3"
  top: "conv3"
  name: "relu3"
  type: RELU
}
layers {
  bottom: "conv3"
  top: "conv4"
  name: "conv4"
  type: CONVOLUTION
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 2
  }
}
layers {
  bottom: "conv4"
  top: "conv4"
  name: "relu4"
  type: RELU
}
layers {
  bottom: "conv4"
  top: "conv5"
  name: "conv5"
  type: CONVOLUTION
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
  }
}
layers {
  bottom: "conv5"
  top: "conv5"
  name: "relu5"
  type: RELU
}
layers {
  bottom: "conv5"
  top: "ip1"
  name: "ip1"
  type: INNER_PRODUCT
  inner_product_param {
    num_output: 30
  }
}
layers {
  bottom: "ip1"
  bottom: "label"
  top: "loss"
  name: "loss"
  type: HINGE_LOSS
}
I0128 18:18:13.020005  3892 net.cpp:67] Creating Layer fkp
I0128 18:18:13.020031  3892 net.cpp:356] fkp -> data
I0128 18:18:13.020066  3892 net.cpp:356] fkp -> label
I0128 18:18:13.020092  3892 net.cpp:96] Setting up fkp
I0128 18:18:13.020112  3892 hdf5_data_layer.cpp:57] Loading filename from train.txt
I0128 18:18:13.020164  3892 hdf5_data_layer.cpp:69] Number of files: 1
I0128 18:18:13.020185  3892 hdf5_data_layer.cpp:29] Loading HDF5 filefacialkp-train.hd5
I0128 18:18:15.200341  3892 hdf5_data_layer.cpp:49] Successully loaded 6000 rows
I0128 18:18:15.200412  3892 hdf5_data_layer.cpp:81] output data size: 100,1,96,96
I0128 18:18:15.200440  3892 net.cpp:103] Top shape: 100 1 96 96 (921600)
I0128 18:18:15.200459  3892 net.cpp:103] Top shape: 100 30 1 1 (3000)
I0128 18:18:15.200498  3892 net.cpp:67] Creating Layer conv1
I0128 18:18:15.200520  3892 net.cpp:394] conv1 <- data
I0128 18:18:15.200546  3892 net.cpp:356] conv1 -> conv1
I0128 18:18:15.200582  3892 net.cpp:96] Setting up conv1
I0128 18:18:15.246759  3892 net.cpp:103] Top shape: 100 96 22 22 (4646400)
I0128 18:18:15.246901  3892 net.cpp:67] Creating Layer relu1
I0128 18:18:15.246919  3892 net.cpp:394] relu1 <- conv1
I0128 18:18:15.246942  3892 net.cpp:345] relu1 -> conv1 (in-place)
I0128 18:18:15.246976  3892 net.cpp:96] Setting up relu1
I0128 18:18:15.247000  3892 net.cpp:103] Top shape: 100 96 22 22 (4646400)
I0128 18:18:15.247020  3892 net.cpp:67] Creating Layer pool1
I0128 18:18:15.247035  3892 net.cpp:394] pool1 <- conv1
I0128 18:18:15.247053  3892 net.cpp:356] pool1 -> pool1
I0128 18:18:15.247074  3892 net.cpp:96] Setting up pool1
I0128 18:18:15.247104  3892 net.cpp:103] Top shape: 100 96 11 11 (1161600)
I0128 18:18:15.247131  3892 net.cpp:67] Creating Layer norm1
I0128 18:18:15.247146  3892 net.cpp:394] norm1 <- pool1
I0128 18:18:15.247164  3892 net.cpp:356] norm1 -> norm1
I0128 18:18:15.247184  3892 net.cpp:96] Setting up norm1
I0128 18:18:15.247206  3892 net.cpp:103] Top shape: 100 96 11 11 (1161600)
I0128 18:18:15.247234  3892 net.cpp:67] Creating Layer conv2
I0128 18:18:15.247248  3892 net.cpp:394] conv2 <- norm1
I0128 18:18:15.247266  3892 net.cpp:356] conv2 -> conv2
I0128 18:18:15.247284  3892 net.cpp:96] Setting up conv2
I0128 18:18:15.249444  3892 net.cpp:103] Top shape: 100 256 11 11 (3097600)
I0128 18:18:15.249547  3892 net.cpp:67] Creating Layer relu2
I0128 18:18:15.249568  3892 net.cpp:394] relu2 <- conv2
I0128 18:18:15.249591  3892 net.cpp:345] relu2 -> conv2 (in-place)
I0128 18:18:15.249619  3892 net.cpp:96] Setting up relu2
I0128 18:18:15.249639  3892 net.cpp:103] Top shape: 100 256 11 11 (3097600)
I0128 18:18:15.249658  3892 net.cpp:67] Creating Layer pool2
I0128 18:18:15.249675  3892 net.cpp:394] pool2 <- conv2
I0128 18:18:15.249692  3892 net.cpp:356] pool2 -> pool2
I0128 18:18:15.249712  3892 net.cpp:96] Setting up pool2
I0128 18:18:15.249735  3892 net.cpp:103] Top shape: 100 256 5 5 (640000)
I0128 18:18:15.249760  3892 net.cpp:67] Creating Layer norm2
I0128 18:18:15.249775  3892 net.cpp:394] norm2 <- pool2
I0128 18:18:15.249793  3892 net.cpp:356] norm2 -> norm2
I0128 18:18:15.249811  3892 net.cpp:96] Setting up norm2
I0128 18:18:15.249827  3892 net.cpp:103] Top shape: 100 256 5 5 (640000)
I0128 18:18:15.249847  3892 net.cpp:67] Creating Layer conv3
I0128 18:18:15.249861  3892 net.cpp:394] conv3 <- norm2
I0128 18:18:15.249878  3892 net.cpp:356] conv3 -> conv3
I0128 18:18:15.249898  3892 net.cpp:96] Setting up conv3
I0128 18:18:15.255113  3892 net.cpp:103] Top shape: 100 384 5 5 (960000)
I0128 18:18:15.255230  3892 net.cpp:67] Creating Layer relu3
I0128 18:18:15.255252  3892 net.cpp:394] relu3 <- conv3
I0128 18:18:15.255275  3892 net.cpp:345] relu3 -> conv3 (in-place)
I0128 18:18:15.255296  3892 net.cpp:96] Setting up relu3
I0128 18:18:15.255314  3892 net.cpp:103] Top shape: 100 384 5 5 (960000)
I0128 18:18:15.255336  3892 net.cpp:67] Creating Layer conv4
I0128 18:18:15.255348  3892 net.cpp:394] conv4 <- conv3
I0128 18:18:15.255365  3892 net.cpp:356] conv4 -> conv4
I0128 18:18:15.255384  3892 net.cpp:96] Setting up conv4
I0128 18:18:15.259575  3892 net.cpp:103] Top shape: 100 384 5 5 (960000)
I0128 18:18:15.259680  3892 net.cpp:67] Creating Layer relu4
I0128 18:18:15.259702  3892 net.cpp:394] relu4 <- conv4
I0128 18:18:15.259726  3892 net.cpp:345] relu4 -> conv4 (in-place)
I0128 18:18:15.259748  3892 net.cpp:96] Setting up relu4
I0128 18:18:15.259768  3892 net.cpp:103] Top shape: 100 384 5 5 (960000)
I0128 18:18:15.259788  3892 net.cpp:67] Creating Layer conv5
I0128 18:18:15.259804  3892 net.cpp:394] conv5 <- conv4
I0128 18:18:15.259820  3892 net.cpp:356] conv5 -> conv5
I0128 18:18:15.259840  3892 net.cpp:96] Setting up conv5
I0128 18:18:15.263234  3892 net.cpp:103] Top shape: 100 256 5 5 (640000)
I0128 18:18:15.263345  3892 net.cpp:67] Creating Layer relu5
I0128 18:18:15.263365  3892 net.cpp:394] relu5 <- conv5
I0128 18:18:15.263386  3892 net.cpp:345] relu5 -> conv5 (in-place)
I0128 18:18:15.263407  3892 net.cpp:96] Setting up relu5
I0128 18:18:15.263427  3892 net.cpp:103] Top shape: 100 256 5 5 (640000)
I0128 18:18:15.263445  3892 net.cpp:67] Creating Layer ip1
I0128 18:18:15.263460  3892 net.cpp:394] ip1 <- conv5
I0128 18:18:15.263478  3892 net.cpp:356] ip1 -> ip1
I0128 18:18:15.263497  3892 net.cpp:96] Setting up ip1
I0128 18:18:15.264796  3892 net.cpp:103] Top shape: 100 30 1 1 (3000)
I0128 18:18:15.264901  3892 net.cpp:67] Creating Layer loss
I0128 18:18:15.264919  3892 net.cpp:394] loss <- ip1
I0128 18:18:15.264940  3892 net.cpp:394] loss <- label
I0128 18:18:15.264958  3892 net.cpp:356] loss -> loss
I0128 18:18:15.264982  3892 net.cpp:96] Setting up loss
I0128 18:18:15.265007  3892 net.cpp:103] Top shape: 1 1 1 1 (1)
I0128 18:18:15.265033  3892 net.cpp:109]     with loss weight 1
I0128 18:18:15.265077  3892 net.cpp:170] loss needs backward computation.
I0128 18:18:15.265094  3892 net.cpp:170] ip1 needs backward computation.
I0128 18:18:15.265108  3892 net.cpp:170] relu5 needs backward computation.
I0128 18:18:15.265122  3892 net.cpp:170] conv5 needs backward computation.
I0128 18:18:15.265141  3892 net.cpp:170] relu4 needs backward computation.
I0128 18:18:15.265156  3892 net.cpp:170] conv4 needs backward computation.
I0128 18:18:15.265171  3892 net.cpp:170] relu3 needs backward computation.
I0128 18:18:15.265187  3892 net.cpp:170] conv3 needs backward computation.
I0128 18:18:15.265202  3892 net.cpp:170] norm2 needs backward computation.
I0128 18:18:15.265218  3892 net.cpp:170] pool2 needs backward computation.
I0128 18:18:15.265233  3892 net.cpp:170] relu2 needs backward computation.
I0128 18:18:15.265250  3892 net.cpp:170] conv2 needs backward computation.
I0128 18:18:15.265264  3892 net.cpp:170] norm1 needs backward computation.
I0128 18:18:15.265280  3892 net.cpp:170] pool1 needs backward computation.
I0128 18:18:15.265296  3892 net.cpp:170] relu1 needs backward computation.
I0128 18:18:15.265311  3892 net.cpp:170] conv1 needs backward computation.
I0128 18:18:15.265326  3892 net.cpp:172] fkp does not need backward computation.
I0128 18:18:15.265341  3892 net.cpp:208] This network produces output loss
I0128 18:18:15.265372  3892 net.cpp:467] Collecting Learning Rate and Weight Decay.
I0128 18:18:15.265399  3892 net.cpp:219] Network initialization done.
I0128 18:18:15.265414  3892 net.cpp:220] Memory required for data: 100555204
Traceback (most recent call last):
  File "output.py", line 19, in <module>
    net = caffe.Classifier(MODEL_FILE, PRETRAINED)
  File "/home/pbu/Desktop/caffe/python/caffe/classifier.py", line 43, in __init__
    self.crop_dims = np.array(self.blobs[self.inputs[0]].data.shape[2:])
IndexError: list index out of range
```

**Comment by shelhamer** [comment]
Closing for mailing list thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/zzoqxAdyPSk/tcO4DYj8mU4J as this is a usage question.
