### ISSUE TITLE
can't run the classification example because of failing to parse caffemodel file

### ISSUE THREAD

**Issue by helxsz** [BVLC/caffe#1936]
Hi, I am new to caffe, and now I am trying out the classification example in python, I had the bvlc_reference_caffenet.caffemodel in right place , but still I got this error, 

```javascript
I0222 07:07:51.960646 29421 net.cpp:219] Network initialization done.
I0222 07:07:51.960654 29421 net.cpp:220] Memory required for data: 62497920
E0222 07:07:53.114240 29421 upgrade_proto.cpp:611] Attempting to upgrade input file specified using deprecated transformation parameters: /home/xs/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0222 07:07:53.114285 29421 upgrade_proto.cpp:614] Successfully upgraded file specified using deprecated data transformation parameters.
E0222 07:07:53.114291 29421 upgrade_proto.cpp:616] Note that future Caffe releases will only support transform_param messages for transformation fields.
Traceback (most recent call last):
  File "classify.py", line 26, in <module>
    image_dims=(256, 256))
  File "/home/xs/caffe/python/caffe/classifier.py", line 35, in __init__
    self.set_mean(self.inputs[0], mean)
  File "/home/xs/caffe/python/caffe/pycaffe.py", line 223, in _Net_set_mean
    mean = caffe.io.resize_image(mean.transpose((1,2,0)),
ValueError: axes don't match array
```

```javascript
net = caffe.Classifier(MODEL_FILE, PRETRAINED,
        mean=np.load(caffe_root+'python/caffe/imagenet/ilsvrc_2012_mean.npy').mean(1).mean(1),
        channel_swap=(2,1,0),
        raw_scale=255,
        image_dims=(256, 256))
```
 any one kindly tell me how to solve it, thanks

**Comment by helxsz** [comment]
```javascript
net = caffe.Classifier(MODEL_FILE, PRETRAINED)
net.set_raw_scale('data',255)
net.set_channel_swap('data',(2,1,0))
net.set_mean('data',np.load(caffe_root+'python/caffe/imagenet/ilsvrc_2012_mean.npy'))
```

I tried the code above, and now it works well.
