### ISSUE TITLE
the  error   when  run  app.py

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2104]
I  have fllowed   https://github.com/BVLC/caffe/pull/2058
and  the  http://0.0.0.0:5000/   can  open  now,but  after  I  choose  the  picture,the  error comes  
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the applicatio

and  the  error  is  like  this:
INFO:tornado.access:200 GET / (127.0.0.1) 23.87ms
INFO:root:Saving to /tmp/caffe_demos_uploads/2015-03-12_13:41:26.382528chow.jpg.
INFO:root:result: [('chow', '0.94320'), ('Tibetan mastiff', '0.02878'), ('Pekinese', '0.00627'), ('Tibetan terrier', '0.00416'), ('golden retriever', '0.00413')]
INFO:root:bet result: [('chow', '3.19765'), ('spitz', '2.62130'), ('dog', '1.22963'), ('domestic animal', '1.15063'), ('canine', '1.11098')]
ERROR:__main__:Exception on /classify_upload [POST]
Traceback (most recent call last):
  File "/home/wzq/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wzq/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wzq/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wzq/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wzq/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "examples/web_demo/app.py", line 78, in classify_upload
    imagesrc=embed_image_html(image)
  File "examples/web_demo/app.py", line 87, in embed_image_html
    image_pil.save(string_buf, format='png')
  File "/home/wzq/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 1673, in save
    save_handler = SAVE[format.upper()]  # unknown format
KeyError: 'PNG'
ERROR:tornado.access:500 POST /classify_upload (127.0.0.1) 3346.83ms

**Comment by wzq12138** [comment]
what  doe  : target_blobs[j]->height() == source_layer.blobs(j).height()   mean

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
