### ISSUE TITLE
Error reported when debugging in Caffe

### ISSUE THREAD

**Issue by you-n-g** [BVLC/caffe#2639]
I'm trying to debug in Caffe
I compile caffe with the command below
```
 CMAKE_BUILD_TYPE=Debug DEBUG=1  make test -j16
```
When it is building caffe, I found  `-g` flag is added  with `ps aux | grep '\-g'`

Then I try to run gdb with caffe I build just now.
```
gdb ./caffe/build/tools/caffe
```

The error below is reported.
```
(gdb) r
Starting program: /root/repos/convnet-benchmarks/caffe/./caffe/build/tools/caffe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.3600.3-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.3600.3-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
```
Actually I can debug with GDB. 
I just want to know why it report these error info.

Hoping someone could point out what's wrong
Thanks  in advance!

**Comment by longjon** [comment]
Closing as this looks like a `gdb` issue rather than a Caffe one. Your `gdb` may be finding the wrong Python installation.
