### ISSUE TITLE
[PYCAFFE] TypeError: __init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by diwgan32** [BVLC/caffe#2660]
I am getting the following error when I try to import caffe in Python. I have made pycaffe, and I believe that I have installed all the correct libraries. 

```javascript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cng2/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/cng2/caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/home/cng2/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/cng2/caffe/python/caffe/proto/caffe_pb2.py", line 23, in <module>
    g_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
```

Does anybody have any idea what could be causing this?

**Comment by liboyue** [comment]
see https://github.com/BVLC/caffe/issues/2092
