### ISSUE TITLE
Weird error during `import caffe`

### ISSUE THREAD

**Issue by tonyyyang** [BVLC/caffe#2763]
When running `import caffe` on the server, I got the following weird error
```
 Traceback (most recent call last):
   File "classify.py", line 3, in <module>
     import caffe
   File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
     from .pycaffe import Net, SGDSolver
   File "/opt/caffe/python/caffe/pycaffe.py", line 14, in <module>
     import caffe.io
   File "/opt/caffe/python/caffe/io.py", line 2, in <module>
     import skimage.io
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/__init__.py", line 15, in <module>
     reset_plugins()
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 89, in reset_plugins
     _load_preferred_plugins()
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 69, in _load_preferred_plugins
     _set_plugin(p_type, preferred_plugins['all'])
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 81, in _set_plugin
     use_plugin(plugin, kind=plugin_type)
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 251, in use_plugin
     _load(name)
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 295, in _load
     fromlist=[modname])
   File "/opt/anaconda/lib/python2.7/site-packages/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
     import matplotlib.pyplot as plt
   File "/opt/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in <module>
     rcParams = rc_params()
   File "/opt/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 947, in rc_params
     fname = matplotlib_fname()
   File "/opt/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 768, in matplotlib_fname
     configdir = _get_configdir()
   File "/opt/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 635, in _get_configdir
     return _get_config_or_cache_dir(_get_xdg_config_dir())
   File "/opt/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 612, in _get_config_or_cache_dir
     return _create_tmp_config_dir()
   File "/opt/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 544, in _create_tmp_config_dir
     tempdir = os.path.join(tempdir, 'matplotlib-%s' % getpass.getuser())
   File "/opt/anaconda/lib/python2.7/getpass.py", line 158, in getuser
     return pwd.getpwuid(os.getuid())[0]
 KeyError: 'getpwuid(): uid not found: 1000'
```

Directly run 
```
import os
import pwd
print(pwd.getpwuid(os.getuid()))
```
get the following 
```
pwd.struct_passwd(pw_name='azureuser', pw_passwd='', pw_uid=1000, pw_gid=1000, pw_gecos='', pw_dir='/', pw_shell='/bin/bash')
```

Have anyone encountered the same error before? Any comments are welcomed.

**Comment by BlGene** [comment]
It looks like this is a skimage problem, check if you can import it by itself, if not it would be best to ask them going wrong.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
