### ISSUE TITLE
Importerror:when i try to import caffe in python,i got the error;

### ISSUE THREAD

**Issue by fanser** [BVLC/caffe#3209]
Traceback (most recent call last):
  File "1.py", line 18, in <module>
    import caffe
  File "/home/fzy/caffe-master/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/fzy/caffe-master/python/caffe/pycaffe.py", line 10, in <module>
    from ._caffe import Net, SGDSolver

ImportError: /home/fzy/caffe-master/python/caffe/_caffe.so: undefined symbol: vdSub

i don't know what is 'vdsub',and i didn't find the information about this! so could you help me to figure out

**Comment by fanser** [comment]
After change the PYTHONPATH,I rebuild caffe.then,it works！
