### ISSUE TITLE
Caffe train fails when encountering an image that can't be loaded

### ISSUE THREAD

**Issue by EvanZ** [BVLC/caffe#3661]
Shouldn't this be easy to catch errors like this and just skip images that don't load? Am I missing a command line option that does something like this? I could be training for hours and then one failed image would waste a lot of compute time.

`E0210 20:59:21.399780  4184 io.cpp:80] Could not open or find file /images/0253cd0102744ed188e703176ddb265a_20141026_bg320.jpg
F0210 20:59:21.400117  4184 image_data_layer.cpp:138] Check failed: cv_img.data Could not load /images/0253cd0102744ed188e703176ddb265a_20141026_bg320.jpg
*** Check failure stack trace: ***
    @     0x7f926548cdaa  (unknown)
    @     0x7f926548cce4  (unknown)
    @     0x7f926548c6e6  (unknown)
    @     0x7f926548f687  (unknown)
    @     0x7f9265abf04c  caffe::ImageDataLayer<>::load_batch()
    @     0x7f9265b79749  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f9265bab220  caffe::InternalThread::entry()
    @     0x7f925d40aa4a  (unknown)
    @     0x7f9259c11182  start_thread
    @     0x7f926487347d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)`

**Comment by SvenTwo** [comment]
I think it's dangerous to just skip the image, because you may have aligned the input images to batches (possibly across multiple input layers) and then you get an offset into your training data which you may not even notice. I like the caffe-approach of "on error, fail completely", because it forces you to fix the errors ;-)

But maybe it could be a layer parameter?

**Comment by EvanZ** [comment]
I see. I suppose in that case, an "image" equal to the mean value might work? Parameter to turn on/off could be nice.

**Comment by seanbell** [comment]
Sure, write a PR (_with unit tests_) and we will review it.

**Comment by toby5box** [comment]
Since this is still open, can I add that on my installation, I get an abort core dump on a missing image, but with no explanation that this is the cause.

Eventually using gdb I was able to get this backtrace which was the clue:

```
I0315 13:03:25.882772 29106 net.cpp:84] Creating Layer fire8/squeeze1x1
I0315 13:03:25.882786 29106 net.cpp:406] fire8/squeeze1x1 <- fire7/concat
I0315 13:03:25.882802 29106 net.cpp:380] fire8/squeeze1x1 -> fire8/squeeze1x1

Thread 5 "caffe" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffbffff700 (LWP 29114)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5bacf5d in __GI_abort () at abort.c:90
#2  0x00007ffff6de94e7 in ?? () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#3  0x00007ffff6de00cd in google::LogMessage::Fail() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#4  0x00007ffff6de1f33 in google::LogMessage::SendToLog() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#5  0x00007ffff6ddfc28 in google::LogMessage::Flush() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#6  0x00007ffff6de2999 in google::LogMessageFatal::~LogMessageFatal() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#7  0x00007ffff735fcb9 in caffe::ImageDataLayer<float>::load_batch(caffe::Batch<float>*) ()
   from /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0
#8  0x00007ffff7335cf8 in caffe::BasePrefetchingDataLayer<float>::InternalThreadEntry() ()
   from /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0
#9  0x00007ffff731a5e7 in caffe::InternalThread::entry(int, caffe::Caffe::Brew, int, int, int, bool) ()
   from /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0
#10 0x00007ffff731b878 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf6<void, caffe::InternalThread, int, caffe::Caffe::Brew, int, int, int, bool>, boost::_bi::list7<boost::_bi::value<caffe::InternalThread*>, boost::_bi::value<int>, boost::_bi::value<caffe::Caffe::Brew>, boost::_bi::value<int>, boost::_bi::value<int>, boost::_bi::value<int>, boost::_bi::value<bool> > > >::run() () from /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0
#11 0x00007ffff595e416 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.62.0
#12 0x00007ffff57357fc in start_thread (arg=0x7fffbffff700) at pthread_create.c:465
#13 0x00007ffff5c88b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Perhaps some log messages could be added to point users to the problem more directly.

**Comment by syalanurag1991** [comment]
Was this issue resolved?

I am still facing this issue.

![image](https://user-images.githubusercontent.com/32419039/93530906-fcd11380-f903-11ea-8985-0d6fd42c100c.png)
