### ISSUE TITLE
 fid.write(draw_net(caffe_net, rankdir, ext)) TypeError: must be string or buffer, not list

### ISSUE THREAD

**Issue by QiJohn** [BVLC/caffe#3922]
when I used the command, python draw_net.py ../models/bvlc_reference_rcnn_ilsvrc13/deploy.prototxt ./deploy.png, to create a picture, an error will come out. The error informations is an follows.

> 
/home/johnqi/caffe/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Net<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/home/johnqi/caffe/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Blob<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/home/johnqi/caffe/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Solver<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
Couldn't import dot_parser, loading of dot files will not be possible.
Drawing net to deploy.png
Warning: /tmp/tmp4mubS3: syntax error in line 1 near '-'

Traceback (most recent call last):
  File "draw_net.py", line 45, in <module>
    main()
  File "draw_net.py", line 41, in main
    caffe.draw.draw_net_to_file(net, args.output_image_file, args.rankdir)
  File "/home/johnqi/caffe/caffe/python/caffe/draw.py", line 222, in draw_net_to_file
    fid.write(draw_net(caffe_net, rankdir, ext))
TypeError: must be string or buffer, not list

**Comment by seanbell** [comment]
Did you install `dot`?  It says `Couldn't import dot_parser`

**Comment by QiJohn** [comment]
yes, I did

**Comment by wadefelix** [comment]
have a try to plot to pdf

**Comment by NateLol** [comment]
Also came across this one running `python draw_net.py deploy.prototxt a.png,` 
deploy.prototxt is from caffe/model/bvlc_reference_rcnn_ilsvrc13

here are the outputs

`Drawing net to a.png
Warning: /tmp/tmpr35OkY: syntax error in line 1 near '-'

Traceback (most recent call last):
  File "draw_net.py", line 46, in <module>
    main()
  File "draw_net.py", line 42, in main
    caffe.draw.draw_net_to_file(net, args.output_image_file, args.rankdir)
  File "/home/nate/caffe/python/caffe/draw.py", line 222, in draw_net_to_file
    fid.write(draw_net(caffe_net, rankdir, ext))
TypeError: must be string or buffer, not list
`

can anyone throw some lights on it?
