### ISSUE TITLE
Error running draw_net.py: pydot.InvocationException

### ISSUE THREAD

**Issue by vladfi1** [BVLC/caffe#3924]
I'm using a fresh install of (py)caffe on Ubuntu 15.10. When I try to run draw_net.py, I get the following error:

```
/home/vlad/Repos/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Net<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/home/vlad/Repos/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Blob<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/home/vlad/Repos/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Solver<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
Drawing net to dqn.png
Traceback (most recent call last):
  File "../caffe/python/draw_net.py", line 45, in <module>
    main()
  File "../caffe/python/draw_net.py", line 41, in main
    caffe.draw.draw_net_to_file(net, args.output_image_file, args.rankdir)
  File "/home/vlad/Repos/caffe/python/caffe/draw.py", line 222, in draw_net_to_file
    fid.write(draw_net(caffe_net, rankdir, ext))
  File "/home/vlad/Repos/caffe/python/caffe/draw.py", line 204, in draw_net
    return get_pydot_graph(caffe_net, rankdir).create(format=ext)
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 2023, in create
    status, stderr_output) )
pydot.InvocationException: Program terminated with status: 1. stderr follows: Error: /tmp/tmpsAHMAX: syntax error in line 1 near '{'
```

I have pydotplus installed via pip.

**Comment by ajtulloch** [comment]
You need a `name: <name>` field in the prototxt you're using IIRC.

**Comment by vladfi1** [comment]
From the error message it looks like the problem is with the dot interface, not the prototxt file. In any case the graph I'm trying to visualize is defined [here](https://github.com/muupan/dqn-in-the-caffe/blob/master/dqn.prototxt).

**Comment by ajtulloch** [comment]
Try adding `name: <name>` in the prototxt.

**Comment by vladfi1** [comment]
Adding the name seems to have worked - draw_net.py now runs and produces a png without error. However, the output is just an white 11x11 pixel square...

**Comment by oopsno** [comment]
Hi, @vladfi1 

I met exactly same problem when trying to visualize the prototxt from [hszhao/PSPNet](https://github.com/hszhao/PSPNet/blob/master/evaluation/prototxt/pspnet50_ADE20K_473.prototxt), and solved it by **upgrading pydot** using pip.

```shell
sudo -H python -m pip install pydot --upgrade
```

p.s. my environment is :
+ Ubuntu 16.04
+ CUDA 8.0
+ cuDNN 5.1
+ pydot (1.0.2 => 1.2.3)
