### ISSUE TITLE
UnicodeDecodeError on downloading models from the model zoo

### ISSUE THREAD

**Issue by aravind-vasudevan** [BVLC/caffe#4129]
Hi all,

I am just starting out with caffe. I have cloned the repo and I have caffe working on my machine. I am trying to download the models from the model zoo using the documentation. I am running the download_model_binary.py and it seems to download the caffemodel file, but throws the following error:
```
./scripts/download_model_binary.py models/bvlc_reference_caffenet/
...100%, 232 MB, 10943 KB/s, 21 seconds passedTraceback (most recent call last):
  File "./scripts/download_model_binary.py", line 74, in <module>
    if not model_checks_out():
  File "./scripts/download_model_binary.py", line 64, in model_checks_out
    return hashlib.sha1(f.read()).hexdigest() == sha1
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 110: invalid start byte
```

It ends up downloading the models, for instance I ran the cpp_classification example with the googlenet model and it predicted fine:
```
/build/examples/cpp_classification/cpp_classification.bin models/bvlc_googlenet/deploy.prototxt models/bvlc_googlenet/bvlc_googlenet.caffemodel data/ilsvrc12/imagenet_mean.binaryproto data/ilsvrc12/synset_words.txt examples/images/cat.jpg 
NVIDIA: no NVIDIA devices found
---------- Prediction for examples/images/cat.jpg ----------
0.5009 - "n02123159 tiger cat"
0.2283 - "n02123045 tabby, tabby cat"
0.1612 - "n02124075 Egyptian cat"
0.0283 - "n02127052 lynx, catamount"
0.0134 - "n02123394 Persian cat"
```

But I am unsure if something else follows from the download script and why this error is being thrown in the first place.

**Comment by seanbell** [comment]
Hm, that download script may be making a `unicode` vs `bytes` error (that you wouldn't notice if using `python2`).

**Comment by aravind-vasudevan** [comment]
I am using `python3.5` should I be seeing this error even then?
