### ISSUE TITLE
about cmake question

### ISSUE THREAD

**Issue by wqlw** [BVLC/caffe#4204]
hello all ,my quetion is here:
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wei/.local/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
    import add_newdocs
  File "/home/wei/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/home/wei/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 4, in <module>
    from type_check import *
  File "/home/wei/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/home/wei/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 5, in <module>
    import multiarray
ImportError: /home/wei/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_AsUnicodeEscapeString
-- Could NOT find NumPy (missing:  NUMPY_INCLUDE_DIR NUMPY_VERSION) (Required is at least version "1.7.1")

take place the errors,but l already installed the NumPy,the question have been existed.would you help me?

**Comment by wqlw** [comment]
the question already was solved now.in detail below!!
I downloaded the .tar.gz package for the version 1.8.0 from here-->(https://sourceforge.net/projects/numpy/files/NumPy/), unpacked it, moved inside the folder and run the commands:

python setup.py build --fcompiler=gnu95
python setup.py install --user

the method helps me my top question,so ,l hope it can help you!@ebadawy

**Comment by jiahuayang** [comment]
@wqlw I has the same issue, and it worked. 

BTW
I can't download numpy from https://sourceforge.net/projects/numpy/files/NumPy/, and I download from here:
https://pypi.python.org/pypi/numpy/1.8.0#downloads
