### ISSUE TITLE
Avoid cuda API calls in destructor

### ISSUE THREAD

**Issue by cysin** [BVLC/caffe#4230]
According to [this](http://stackoverflow.com/questions/35815597/cuda-call-fails-in-some-singleton-global-variables-destructor-when-using-map/35828076#35828076), cuda API calls should be avoided in destructor. I've tried caffe with GTX 1080 and CUDA 8 and encountered error caused by the cuda API calls in destructors of syncedmem.cpp. Thanks

**Comment by flx42** [comment]
In destructors of **global variables**

**Comment by cysin** [comment]
Excuse me if I am wrong. I thought the error was caused by cuda API calling after context destroying. But the code has been running very well with cuda 7.5 and 980 Ti. So this might not be an issue with caffe itself but I really have no idea what's going wrong. This error is like 'ghost' after upgrading to cuda 8 rc and 1080, it could happen or not when doing same test. So any advices?
Here is backtrace of the error:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0531 10:28:36.928508  5156 syncedmem.cpp:56] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb77fe700 (LWP 5156)]
0x00007ffff549e5f7 in raise () from /lib64/libc.so.6
(cuda-gdb) bt

#0  0x00007ffff549e5f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff549fce8 in abort () from /lib64/libc.so.6
#2  0x00007fffddc107d9 in google::logging_fail() () from ../lib/libglog.so.0
#3  0x00007fffddc11e6d in google::LogMessage::Fail() () from ../lib/libglog.so.0
#4  0x00007fffddc13ced in google::LogMessage::SendToLog() () from ../lib/libglog.so.0
#5  0x00007fffddc11a5c in google::LogMessage::Flush() () from ../lib/libglog.so.0
#6  0x00007fffddc1463e in google::LogMessageFatal::~LogMessageFatal() () from ../lib/libglog.so.0
#7  0x00007fffe1ae27b1 in caffe::SyncedMemory::to_gpu() () from ../lib/libcaffe.so.1.0.0
#8  0x00007fffe1ae1b49 in caffe::SyncedMemory::mutable_gpu_data() () from ../lib/libcaffe.so.1.0.0
#9  0x00007fffe19c3892 in caffe::Blob<float>::mutable_gpu_data() () from ../lib/libcaffe.so.1.0.0
#10 0x00007fffe19f41c8 in caffe::BaseConvolutionLayer<float>::forward_gpu_gemm(float const*, float const*, float*, bool) () from ../lib/libcaffe.so.1.0.0
#11 0x00007fffe1b3dd16 in caffe::ConvolutionLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) () from ../lib/libcaffe.so.1.0.0
#12 0x00007fffe1b1fe68 in caffe::Net<float>::ForwardFromTo(int, int) () from ../lib/libcaffe.so.1.0.0
#13 0x00007fffe1b201e7 in caffe::Net<float>::Forward(float*) () from ../lib/libcaffe.so.1.0.0
#14 0x00007fffe1b203ba in caffe::Net<float>::Forward(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, float*) ()
   from ../lib/libcaffe.so.1.0.0

```

**Comment by flx42** [comment]
The problem you mentioned in your initial comment can only occur when the program terminates, you might see the CUDA API calls starting to fail.
In this case, it doesn't seem to be at program termination (looking at the backtrace), so the problem is likely different.
