### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Net'

### ISSUE THREAD

**Issue by newzhx** [BVLC/caffe#4276]
i meet a strange question:
when i defines a net using caffe.Net, there is an error:
AttributeError: 'module' object has no attribute 'Net'

>>> import caffe
>>> net=caffe.Net()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Net'

And there is another one:
python /././caffe/python/classify.py --model ./bvlc_reference_caffenet/deploy.prototxt --weights ./bvlc_reference_caffenet/bvlc-reference_caffenet.caffemodel --gpu

Failed to include caffe_pb2, things might go wrong!
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1113, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ndscbigdata/caffe/python/classify.py", line 14, in <module>
    import caffe
  File "/home/ndscbigdata/caffe/python/caffe/__init__.py", line 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "/home/ndscbigdata/caffe/python/caffe/proto/caffe_pb2.py", line 799, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/descriptor.py", line 845, in _ParseOptions
    message.ParseFromString(string)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1097, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by seanbell** [comment]
This looks like caffe was incorrectly installed.  Please follow up on the mailing list for installation questions.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
