### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__caffe)

### ISSUE THREAD

**Issue by monajalal** [BVLC/caffe#4622]
Do you know how I can fix this problem?

```
(cv) jalal@klein:~/computer_vision/py-faster-rcnn$ ./tools/demo.py 
Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/jalal/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/home/jalal/computer_vision/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/jalal/computer_vision/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define init function (PyInit__caffe)
```

I am using Python 3.4.3+, Ubuntu 15.10, CuDNN V4, Cuda 7.5 and OpenCV3 for Python3.

Any guidance is really appreciated specially from the users who got this working with Python3.

**Comment by shelhamer** [comment]
Sorry, I can't reproduce this in Caffe master but it might be an issue at py-faster-rcnn for Python. Ask at the fork.
