### ISSUE TITLE
Facing issue with bringing up the flash server (web demo)

### ISSUE THREAD

**Issue by jitenoswal** [BVLC/caffe#4706]
Sry if this is something I missed to read in the documentation but I'm facing this issue. Any help is really appreciated. Thanks in advance.

I followed the installation and complication steps. 
 
ran make test with following pass results: 

```
[----------] Global test environment tear-down
[==========] 1096 tests from 150 test cases ran. (42825 ms total)
[  PASSED  ] 1096 tests.
```

Verified all followed exist as mentioned in the web demo setup steps but start web app failed with import caffe error:
 
```
jos:caffe joswal$ ./scripts/
build_docs.sh                deploy_docs.sh               gather_examples.sh
copy_notebook.py             download_model_binary.py     travis/
cpp_lint.py                  download_model_from_gist.sh  upload_model_to_gist.sh

jos:caffe joswal$ ./scripts/download_model_binary.py models/
bvlc_alexnet/                 bvlc_reference_caffenet/      finetune_flickr_style/
bvlc_googlenet/               bvlc_reference_rcnn_ilsvrc13/

jos:caffe joswal$ python examples/web_demo/app.py

Traceback (most recent call last):
  File "examples/web_demo/app.py", line 18, in <module>
    import caffe
ImportError: No module named caffe
```

**Comment by jitenoswal** [comment]
Ok. Good News. I resolved all the environment/setup issues. Now just left on the final issue. And I guess its something related to something specific to code:

```
File "examples/web_demo/app.py", line 99, in <module>
    class ImagenetClassifier(object):
  File "examples/web_demo/app.py", line 115, in ImagenetClassifier
    "File for {} is missing. Should be at: {}".format(key, val))
Exception: File for class_labels_file is missing. Should be at: /Users/joswal/gitRepo/imageClassification/blvc/caffe/data/ilsvrc12/synset_words.txt
```

**Comment by jitenoswal** [comment]
Not sure if I was suppose to copy over the txt file but I did that. And now the error is following:

```
jos:caffe$ python examples/web_demo/app.py
Traceback (most recent call last):
  File "examples/web_demo/app.py", line 99, in <module>
    class ImagenetClassifier(object):
  File "examples/web_demo/app.py", line 115, in ImagenetClassifier
    "File for {} is missing. Should be at: {}".format(key, val))
Exception: File for pretrained_model_file is missing. Should be at: /Users/joswal/gitRepo/imageClassification/blvc/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
```
