### ISSUE TITLE
Mac import caffe error

### ISSUE THREAD

**Issue by anbai106** [BVLC/caffe#4864]
I finally install caffe on my Mac, without error for 'make pycaffe' and 'make distribute', so I got to <caffe-root>/python, and run python -c "import caffe", but I got some errors here, It seems it's the problem of protocol buffers, I am not sure:

python -c 'import caffe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "caffe/proto/caffe_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/protobuf-3.1.0-py2.7-macosx-10.6-x86_64.egg/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/protobuf-3.1.0-py2.7-macosx-10.6-x86_64.egg/google/protobuf/pyext/_message.so, 2): Symbol not found: __ZNK6google8protobuf10TextFormat17FieldValuePrinter10PrintBytesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  Referenced from: /Users/junhao.wen/anaconda2/lib/python2.7/site-packages/protobuf-3.1.0-py2.7-macosx-10.6-x86_64.egg/google/protobuf/pyext/_message.so
  Expected in: flat namespace
 in /Users/junhao.wen/anaconda2/lib/python2.7/site-package

To install caffe is really headache, can someone give me a hand to tell me what happended???
Thanks in advance

**Comment by anbai106** [comment]
I think the problem is because of when I run some python dependencies for pycaffe, they use pip, and I use anaconda pip, So I got some errors like this:
snappy/snappy.cc -o build/temp.macosx-10.6-x86_64-2.7/./snappy/snappy.o -I./leveldb/include -I./leveldb -I./snappy -I. -fno-builtin-memcmp -O2 -fPIC -DNDEBUG -DSNAPPY -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -Wno-error=unused-command-line-argument-hard-error-in-future
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  cc1plus: error: -Werror=unused-command-line-argument-hard-error-in-future: no option -Wunused-command-line-argument-hard-error-in-future
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for leveldb
  Running setup.py clean for leveldb
Failed to build leveldb
Installing collected packages: leveldb
  Running setup.py install for leveldb ... error
    Complete output from command /Users/junhao.wen/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5r/10gy0dnn1x1dykzyb4117pcc000hzl/T/pip-build-byQK6_/leveldb/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/5r/10gy0dnn1x1dykzyb4117pcc000hzl/T/pip-ECNpMF-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'leveldb' extension
    creating build
    creating build/temp.macosx-10.6-x86_64-2.7
    creating build/temp.macosx-10.6-x86_64-2.7/snappy
    creating build/temp.macosx-10.6-x86_64-2.7/leveldb
    creating build/temp.macosx-10.6-x86_64-2.7/leveldb/db
    creating build/temp.macosx-10.6-x86_64-2.7/leveldb/table
    creating build/temp.macosx-10.6-x86_64-2.7/leveldb/util
    creating build/temp.macosx-10.6-x86_64-2.7/leveldb/port
    gcc -fno-strict-aliasing -I/Users/junhao.wen/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/junhao.wen/anaconda2/include/python2.7 -c ./snappy/snappy.cc -o build/temp.macosx-10.6-x86_64-2.7/./snappy/snappy.o -I./leveldb/include -I./leveldb -I./snappy -I. -fno-builtin-memcmp -O2 -fPIC -DNDEBUG -DSNAPPY -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -Wno-error=unused-command-line-argument-hard-error-in-future
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    cc1plus: error: -Werror=unused-command-line-argument-hard-error-in-future: no option -Wunused-command-line-argument-hard-error-in-future
    error: command 'gcc' failed with exit status 1

So how can I install pip leveldb within anaconda?

**Comment by lironmo** [comment]
same error, any progress?
