### ISSUE TITLE
Failed to include caffe_pb2,  while doing import caffe in python 3.5

### ISSUE THREAD

**Issue by surajitsaikia27** [BVLC/caffe#5170]
# Hi guys. I am trying to install caffe, and I have successfully ran the commands "make all, make test, make pycaffe". But, while i am trying to import caffe, I am getting this error "Failed to include caffe_pb2, things might go wrong". I am using Python3.5 Anaconda

 import caffe
Failed to include caffe_pb2, things might go wrong!
  Traceback (most recent call last):
  File "/home/surajit/anaconda3/lib/python3.5/site-   packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
 if self._InternalParse(serialized, 0, length) != length:
  File "/home/surajit/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/home/surajit/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/surajit/caffe-master/python/caffe/__init__.py", line 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "/home/surajit/caffe-master/python/caffe/proto/caffe_pb2.py", line 799, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "/home/surajit/anaconda3/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 869, in _ParseOptions
    message.ParseFromString(string)
  File "/home/surajit/anaconda3/lib/python3.5/site-packages/google/protobuf/message.py", line 185, in   ParseFromString
  self.MergeFromString(serialized)
 File "/home/surajit/anaconda3/lib/python3.5/site packages/google/protobuf/internal/python_message.py", line 1093, in MergeFromString   raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by Cubbee** [comment]
I guess you should compile caffe with protobuf v.3 if you want to use python 3.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
