### ISSUE TITLE
Issues for implement custom layer 

### ISSUE THREAD

**Issue by xujunpeng** [BVLC/caffe#5172]
Hi,

I am pretty new for caffe and currently trying to implement an unpool layer for caffe. I just follow the codes from https://github.com/HyeonwooNoh/caffe which already has a unpool layer.

But when I test this new layer using pycaffe, where I used the code:
def muFun()
  n = caffe.NetSpec()
  ......
  n.unpool11  = L.Unpooling( n.pool11, n.mask11, kernel_size=2, stride=2)  )
  return n.to_proto()

It always shows following message:
Traceback (most recent call last):
  File "net.py", line 98, in <module>
    f.write(str(docNet('min/train_lmdb', 32)))
  File "net.py", line 95, in docNet
    return n.to_proto()
  File "/nfs/isicvlnas01/users/xpeng/tparty/caffe/2016.11.01/python/caffe/net_spec.py", line 189, in to_proto
    top._to_proto(layers, names, autonames)
  File "/nfs/isicvlnas01/users/xpeng/tparty/caffe/2016.11.01/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/nfs/isicvlnas01/users/xpeng/tparty/caffe/2016.11.01/python/caffe/net_spec.py", line 158, in _to_proto
    assign_proto(layer, k, v)
  File "/nfs/isicvlnas01/users/xpeng/tparty/caffe/2016.11.01/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'stride'

I am not sure where is the problem, and could someone give me some helps?

Thanks,
xp

**Comment by williford** [comment]
I've updated a lot of the code from Noh's repository here:
https://github.com/williford/segmentation-caffe
Perhaps this is helpful, if you haven't already fixed your problem.

**Comment by xujunpeng** [comment]
It works. Really appreciate your help.
