### ISSUE TITLE
Build succeed but cannot run because of an issue with the shared object

### ISSUE THREAD

**Issue by fabianfrz** [BVLC/caffe#5175]
### Issue summary

The shared object seems to be not correctly linked or does not find a symbol after it has been compiled successfully.
```
Traceback (most recent call last):
  File "file.py", line 17, in <module>
    import caffe
  File "/usr/local/lib/python3.6/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/usr/local/lib/python3.6/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /usr/local/lib/python3.6/site-packages/caffe/_caffe.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```
### Steps to reproduce

compile it using cmake:
```
cmake .. -Dpython_version=3.6 -DBOOST_INCLUDEDIR=/usr/include/boost148/ -DBOOST_LIBRARYDIR=/usr/lib64/boost148/ -DPYTHON_LIBRARIES=/usr/local/lib/python3.6/ -DPYTHON_EXECUTABLE=/usr/local/bin/python3.6 -DCMAKE_INSTALL_PREFIX:PATH=/usr
```
copy the python code into its include path so it is visible to applications

### Your system configuration
Operating system: CentOS 6
Compiler: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   1.0.0-rc4-2-g365ac88-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   ON
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.48)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.3.0)
--   lmdb              :   Yes (ver. 0.9.18)
--   LevelDB           :   Yes (ver. 1.7)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 2.4.13.2)
--   CUDA              :   No
-- 
-- Python:
--   Interpreter       :   /usr/local/bin/python3.6 (ver. 3.6)
--   Libraries         :   /usr/local/lib/libpython3.6m.a (ver 3.6.0)
--   NumPy             :   /usr/local/lib/python3.6/site-packages/numpy/core/include (ver 1.11.3)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /usr
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/caffe/build
```

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
