### ISSUE TITLE
python scipy dependency library

### ISSUE THREAD

**Issue by lolongcovas** [BVLC/caffe#551]
Hi,

I've compiled pycaffe correctly and then I run example_visualization.py I got the following error message:

Traceback (most recent call last):
  File "example_visualization.py", line 10, in <module>
    import caffe
  File "../python/caffe/**init**.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "../python/caffe/pycaffe.py", line 11, in <module>
    import caffe.io
  File "../python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/**init**.py", line 14, in <module>
    from .collection import *
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/collection.py", line 12, in <module>
    from ._io import imread
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 17, in <module>
    from skimage.color import rgb2grey
  File "/usr/local/lib/python2.7/dist-packages/skimage/color/__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "/usr/local/lib/python2.7/dist-packages/skimage/color/colorconv.py", line 54, in <module>
    from scipy import linalg
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/**init**.py", line 157, in <module>
    from .misc import *
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/misc.py", line 5, in <module>
    from . import blas
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/blas.py", line 131, in <module>
    from scipy.linalg import _fblas
ImportError: /usr/local/lib/python2.7/dist-packages/scipy/linalg/_fblas.so: undefined symbol: ATL_dptsyrk

I've installed openblas, libblas, liblapack. My OS is ubuntu 12.04. Anybody knows why?

thanks

**Comment by sjoycode** [comment]
Hi @lolongcovas 
How did you solve the problem? I have referred to https://www.biostars.org/p/94454/#94524 but I can not sudo as I don't have superuser access. I am running Ubuntu 14.04 LTS. I am getting the same error. 

from scipy.linalg import _fblas
ImportError: /usr/local/lib/python2.7/dist-packages/scipy/linalg/_fblas.so: undefined symbol: ATL_dptsyrk

**Comment by kracwarlock** [comment]
same here

**Comment by ChenluJi** [comment]
I installed the scipy by brew install and the same problem occurred. I solved it by brew uninstall scipy and pip install scipy.
