### ISSUE TITLE
ImportError: You used to compile with protoc --python_out=./ ./caffe.proto

### ISSUE THREAD

**Issue by meanmee** [BVLC/caffe#5735]
I am trying to convert a caffe model to mxnet model using conver_model.py provided by mxnet/tools/caffe_converter.But the following error raised, I googled it but seems no one has the problem same to me. Can anyone solve it? thanks vvery much!

Traceback (most recent call last):
File "convert_model.py", line 6, in 
import caffe_parser
File "/home/wuxiaomin/anaconda2/lib/python2.7/site-packages/mxnet/tools/caffe_converter/caffe_parser.py", line 12, in 
raise ImportError('You used to compile with protoc --python_out=./ ./caffe.proto')
ImportError: You used to compile with protoc --python_out=./ ./caffe.proto

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: gcc5.4
CUDA version (if applicable): 8.0
CUDNN version (if applicable):
BLAS: openBLAS
Python

**Comment by deepali-c** [comment]
Looks like it is not able to import the required package. 
Could you please check if the following works on python prompt:
```
import caffe
from caffe.proto import caffe_pb2
```
