### ISSUE TITLE
ModuleNotFoundError: No module named 'compiler'

### ISSUE THREAD

**Issue by sajjad-taheri** [BVLC/caffe#5759]
After cloning new version of Caffe, I get this error when import caffe:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/caffe/python/caffe/__init__.py", line 9, in <module>
    from .net_gen import metalayers, fix_input_dims
  File "/caffe/python/caffe/net_gen.py", line 12, in <module>
    from compiler.ast import nodes
ModuleNotFoundError: No module named 'compiler'

make all, make test, make runtest and make pycaffe were done without any problem. However, I believe the net_gen.py file uses some deprecated python 2 code.

**Comment by wookay** [comment]
I commented out that line and changed to be enclosed within the print statements.
https://github.com/wookay/caffe/commit/cf8a23d7299296c10e9f3f01f8a28964da846694

I don't test with python 2.7, python 3.5.

I'm using the `opencl` branch with python 3.
```python
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
