### ISSUE TITLE
make pytest    import error, help, please

### ISSUE THREAD

**Issue by 13971073623** [BVLC/caffe#5794]
Mac osx 10.12.5 

Make python successfully.
but,when I make pytest, I got several error information list as this: who can tell me what shall I do? THKs

kimatoMacBook-Pro:caffe huangtao$ make pytest
cd python; python -m unittest discover -s caffe/test
EEEEEEEEEE
======================================================================
ERROR: test_coord_map (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_coord_map
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/huangtao/caffe/python/caffe/test/test_coord_map.py", line 6, in <module>
    import caffe
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dlopen(caffe/_caffe.so, 2): Symbol not found: __ZN7Iex_2_213throwErrnoExcERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
  Referenced from: /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib
  Expected in: /usr/local/opt/ilmbase/lib/libIex-2_2.12.dylib
 in /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by 13971073623** [comment]
I'm sorry I can not us https://groups.google.com/forum/#!forum/caffe-users to submit my problems, because of I'm in China. So permit me to use this place to submit my problems,please.
