### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by woshigcy** [BVLC/caffe#6056]
I met a problem when "import caffe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/proto/caffe_pb2.py", line 797, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'

**Comment by Noiredd** [comment]
Are you using some old version of Protobuf? `_ParseOptions` calls in my caffe_pb2.py look entirely different:  
`options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),`

I saw you posted the same issue to yjxiong/temporal-segment-networks#158 and solved this - mind sharing some details, for future reference?
