### ISSUE TITLE
Installing Using the Python interface

### ISSUE THREAD

**Issue by stavBodik** [BVLC/caffe#6107]
Hi I want to use caffe in python project and I have Anaconda installed, I am using Windows .
I did run the commands to download the necessary packages.
Can I pass the steps with the compiling ( cmake ) ? 
Or just coping the caffe folder into site-packages is enough ? 

I think because I am using windows I cant figure out how to install it right...
Cant use the make with windows, when trying to import caffe  :

`Traceback (most recent call last):
  File "I:/PycharmProjects/Classification_Geokom/deleteme.py", line 2, in <module>
    import caffe
  File "C:\Anaconda3\lib\site-packages\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net
  File "C:\Anaconda3\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named 'caffe._caffe'`

Thanks !

**Comment by stavBodik** [comment]
Found solution , so before copying the python/caffe folder to site-packages ,
use this repository for simple compile and build caffe for windows :

https://github.com/BVLC/caffe/tree/windows/scripts

just run build_win.cmd with correct configurations and everything is good (:
