### ISSUE TITLE
RCNN

### ISSUE THREAD

**Issue by wangzeng1992** [BVLC/caffe#6185]
Python or MATLAB version (for pycaffe and matcaffe respectively):
`Traceback (most recent call last):
  File "D:/VS2013/caffe/caffe-master/Build/x64/Release/pycaffe/detect.py", line 97, in <module>
    detect(pretrained_model, model_def, mean_file, input_file)
  File "D:/VS2013/caffe/caffe-master/Build/x64/Release/pycaffe/detect.py", line 62, in detect
    predictions_df = pd.DataFrame(np.vstack(spec_df.prediction.values), columns=labels_df['name'])
  File "D:\Anaconda\lib\site-packages\pandas\core\frame.py", line 306, in __init__
    copy=copy)
  File "D:\Anaconda\lib\site-packages\pandas\core\frame.py", line 483, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "D:\Anaconda\lib\site-packages\pandas\core\internals.py", line 4303, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "D:\Anaconda\lib\site-packages\pandas\core\internals.py", line 4280, in construction_error
    passed, implied))
ValueError: Shape of passed values is (200, 1673), indices imply (1000, 1673)
Who can help me?? how can i fix it? thanks very much!`

**Comment by wadefelix** [comment]
你的shape对不上啊。
检查prototxt，检查batchsize等配置。 具体嘛，你提供的信息太少啊。

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Please make your request more readable when posting to the caffe-users list. Also describe more clearly what were you doing.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
