### ISSUE TITLE
ld: library not found for -lboost_python (when doing "make pycaffe")

### ISSUE THREAD

**Issue by hammadullah125** [BVLC/caffe#6435]
**I'm trying to install caffe on my Mac machine. I have followed all the steps and also made necessary changes to the MakeFile.config. Everything was successful until "make pycaffe". Now every time when I'm trying to execute "make pycaffe" it throws this error**

CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
In file included from python/caffe/_caffe.cpp:17:
In file included from ./include/caffe/caffe.hpp:12:
./include/caffe/net.hpp:41:5: warning: unused typedef
  'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
LOG_EVERY_N(WARNING, 1000) << "DEPRECATED: ForwardPrefilled() "
^
/usr/local/include/glog/logging.h:943:30: note: expanded from macro
  'LOG_EVERY_N'
                         INVALID_REQUESTED_LOG_SEVERITY);           \
                         ^
1 warning generated.
ld: library not found for -lboost_python
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python/caffe/_caffe.so] Error 1

**I tried installing "brew install/reinstall boost-python" and also "brew install boost-python3" but it shows this**

Error: undefined method `sha1' for #<Class:0x007fb47f268988>
Please report this bug:
https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:4:in     
`<class:Boost>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:1:in     
`load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in 
`load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:281:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:70:in `block in 
resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:55:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:55:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:10:in `<main>'

**Any kind of help/hint will be appreciated. Thanks**

**Comment by Gusminha** [comment]
Hi @hammadullah,
I solved this problem doing this:
In the lboost_python include location (mine is at /usr/lib/x86_64-linux-gnu, with name libboost_python) 
Find the actual version:
#ls -l | grep libboost_python
And do
#ln -s libboost_python-py35.so.x.xx.x libboost_python3.so

**Comment by hammadullah125** [comment]
Thanks for your reply. I did that already and it solved my problem. After this my "make pycaffe" was successful and I exported the path in the ~/.bash_profile but whenever I was importing caffe it was giving error. When I searched that error I came across a solution which was (in the below image)

<img width="715" alt="screen shot 2018-06-24 at 11 41 03 am" src="https://user-images.githubusercontent.com/6536632/41817859-884efd62-77a3-11e8-9d42-1f557f895c32.png">

But after doing all this and "make clean; make all" again, everything was fine. Now when I'm doing "make pycaffe" again, I'm getting a new error which is I'm unable able to solve. The problem is 

Hammads-MBP:caffe Screamer$ make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
In file included from python/caffe/_caffe.cpp:17:
In file included from ./include/caffe/caffe.hpp:12:
./include/caffe/net.hpp:41:5: warning: unused typedef
      'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
    LOG_EVERY_N(WARNING, 1000) << "DEPRECATED: ForwardPrefilled() "
    ^
/usr/local/include/glog/logging.h:943:30: note: expanded from macro
      'LOG_EVERY_N'
                             INVALID_REQUESTED_LOG_SEVERITY);           \
                             ^
1 warning generated.
ld: library not found for -lpython2.7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python/caffe/_caffe.so] Error 1

**Comment by benxgh1996** [comment]
I believe I ran into a very similar (if not the same) problem. I am using python 2 though, more specifically anaconda python. This thread helps me fix the problem: https://stackoverflow.com/questions/49961216/pycaffe-build-fails-lboost-python-not-found. There is another thread that might help with python3: https://stackoverflow.com/questions/40616527/build-caffe-with-python-cannot-find-lboost-python3.
