### ISSUE TITLE
window_cuda9.0

### ISSUE THREAD

**Issue by beifengche** [BVLC/caffe#6471]
### System configuration

* Operating system:  windows10
* Compiler: vs2015
* CUDA version (if applicable): 9.0
* CUDNN version (if applicable): 7.0
* BLAS: openblas
* Python version (if using pycaffe): 2.7
* MATLAB version (if using matcaffe): null

### Issue checklist
Does windows support cuda9.0?

**Comment by mineo210** [comment]
Yes, But its a pain in the ass to get it working

**Comment by gfursin** [comment]
You can try to install CK as described here: https://github.com/ctuning/ck#windows
and then try to install Caffe using related CK package:

```
$ ck pull repo --url=https://github.com/dividiti/ck-caffe
$ ck install package:lib-caffe-bvlc-master-cudnn-universal --env.CAFFE_BUILD_PYTHON=ON
```

CK should automatically detect your Visual Studio, CUDA, cuDNN and attempt to build Caffe - hope it will work ...

From the back of my mind, I didn't have problems with CUDA 9.0 when using VS 2015. Current problems are when using CUDA 9.x with the latest VS 2017 release.

**Comment by wyasuda** [comment]
Hi,
I would like to install caffe in my Windows7 PC.
Currently, I had installed TensorFlow with CUDA9.0, cuDNN7.0.5 and VisualStudio2015 manually.
It works fine.
Now I have installed VisualStudio2017 in my PC for other projects.
I know CUDA9.0 has some problems with latest VS2017.
So would you tell me how to select VS2015 when I run `ck install` even if my PC has VS2017 also?

**Comment by gfursin** [comment]
Hi @wyasuda . 

You just need to register VS2015 in the CK virtual environment using this command:
```
ck detect soft:compiler.microsoft
```
CK will search for all installations of VS and will then ask you to choose which one you want to register in the CK virtual environment. You should select your VS 2015 installation and normally that's all. 

After that, when you build Caffe via CK, you will be asked which VS version to use from all registered in the CK environment, i.e. either VS2015 or VS2017. 

CK will then explicitly substitute all required environment variables and command lines for cmake and other tools to minimize guessing and non-determinism ...

In fact, you can install or detect multiple versions of different software via CK on Windows, Linux or MacOS in the same way using shared CK modules:
* http://cknowledge.org/shared-soft-detection-plugins.html
* http://cknowledge.org/shared-packages.html

Please tell me if it works.

**Comment by wyasuda** [comment]
Hi @gfursin ,

I run the command below.

`ck detect soft:compiler.microsoft`

Then I got an error below.
If you could give me advices, it would be appreciated.

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = msdk (Microsoft SDK):
Traceback (most recent call last):
  File "C:\Users\yasuda\Miniconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\yasuda\Miniconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\yasuda\Miniconda2\lib\site-packages\ck\kernel.py", line 9593, in <module>
    r=access(sys.argv[1:])
  File "C:\Users\yasuda\Miniconda2\lib\site-packages\ck\kernel.py", line 9549, in access
    rr=perform_action(i)
  File "C:\Users\yasuda\Miniconda2\lib\site-packages\ck\kernel.py", line 3449, in perform_action
    return a(i)
  File "C:\Users\yasuda\CK\ck-env\module\soft\module.py", line 84, in detect
    return check(i)
  File "C:\Users\yasuda\CK\ck-env\module\soft\module.py", line 1620, in check
    rx=ck.access(ii)
  File "C:\Users\yasuda\Miniconda2\lib\site-packages\ck\kernel.py", line 9549, in access
    rr=perform_action(i)
  File "C:\Users\yasuda\Miniconda2\lib\site-packages\ck\kernel.py", line 3449, in perform_action
    return a(i)
  File "C:\Users\yasuda\CK\ck-env\module\env\module.py", line 1432, in resolve
    rx=set(ii)
  File "C:\Users\yasuda\CK\ck-env\module\env\module.py", line 256, in set
    ro=readable_os({'setup':setup})
  File "C:\Users\yasuda\CK\ck-env\module\env\module.py", line 1755, in readable_os
    setup_value = setup.get(setup_key)
NameError: global name 'setup' is not defined

**Comment by willyd** [comment]
As an alternative you can try my latest conda packages. See https://github.com/BVLC/caffe/issues/6569#issuecomment-432491851.
