### ISSUE TITLE
ImportError: caffe.so: undefined symbol: _ZN5caffe21PyErrReportAndForwardEv

### ISSUE THREAD

**Issue by zhangfeng3304** [BVLC/caffe#6497]
Hi Caffe users,

I have built caffe using:

make all
make test
make runtest
make pycaffe

and everything runs smoothly, with 2 disabled tests.

However, error occurs when i try to import caffe in python console:

>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/Programs/Caffe/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, \
  File "/home/nvidia/Programs/Caffe/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/nvidia/Programs/Caffe/caffe/python/caffe/_caffe.so: undefined symbol: _ZN5caffe21PyErrReportAndForwardEv

what's the meaning of _ZN5caffe21PyErrReportAndForwardEv?

**Comment by Noiredd** [comment]
Please read the checklist in the [issue template](https://github.com/BVLC/caffe/blob/master/.github/ISSUE_TEMPLATE.md) and complete your issue accordingly:
>read the guidelines and remove the first paragraph
>write a short summary and detailed steps to reproduce
>explain how solutions to related problems failed (tick if found none)
>fill system configuration
>attach relevant logs/config files (tick if not applicable)

**Comment by chenpengf0223** [comment]
@zhangfeng3304 
HI，I have the same error, did you fix it？
