### ISSUE TITLE
is support Visual Studio 2015, CUDA 9.x, Python 3.5/3.6/3.7?

### ISSUE THREAD

**Issue by cuixing158** [BVLC/caffe#6569]
Dose this caffe support Visual Studio 2015/2017, CUDA 9.x, Python 3.5/3.6/3.7?

Because now with the upgrade of hardware devices, many have not been updated, I hope the official can solve such problems, thank you！

**Comment by Luminisc** [comment]
+1, I have VS 2017, CUDA 9 and Python 3.7, and I can't build project because there are only settings for VS2015 + Python 3.5

**Comment by willyd** [comment]
I will merge a PR (in a few days) that improves the windows CMake build and supports building with vcpkg and conda. Once few people validate that those packages are working I will merge the changes to the windows branch.

Installation should be as simples as:

```
conda create -n caffe
conda config --add channels anaconda
conda install caffe -c willyd
```

I will post back when this is ready to test.

I currently have packages for win64 caffe cpu, CUDA 9.0, python 3.5, 3.6, 3.7.

**Comment by willyd** [comment]
I have published conda packages. Please install with these commands:

```batch
REM Create a new conda environment to install Caffe
REM You can use python 3.5, 3.6 or 3.7
conda create -n caffe python=3.7
REM activate the environment
REM Depending on your conda version you may have to use activate caffe
conda activate caffe
REM add the anaconda channel to resolve all dependencies
conda config --add channels ananconda
REM Install caffe with cuda support or install caffe-cpu if you do not want CUDA support
conda install caffe -c willyd
```

Currently only CUDA 9.0 is built but I will merge the files to build the packages once I have confirmation that the packages work.

**Comment by Franzisdrak** [comment]
> I have published conda packages. Please install with these commands:
> 
> ```batchfile
> REM Create a new conda environment to install Caffe
> REM You can use python 3.5, 3.6 or 3.7
> conda create -n caffe python=3.7
> REM activate the environment
> REM Depending on your conda version you may have to use activate caffe
> conda activate caffe
> REM add the anaconda channel to resolve all dependencies
> conda config --add channels ananconda
> REM Install caffe with cuda support or install caffe-cpu if you do not want CUDA support
> conda install caffe -c willyd
> ```
> 
> Currently only CUDA 9.0 is built but I will merge the files to build the packages once I have confirmation that the packages work.

Careful when copying there is a small typo at channels "anaNconda"

**Comment by willyd** [comment]
Thanks @Franzisdrak I edited the comment accordingly. Have you tried the conda packages? Did they work for you?

**Comment by Franzisdrak** [comment]
@willyd Yeah i am trying. But i am running into one issue after another. Currently:

```
Please make sure either Visual Studio or C++ Build SKU is installed.
-- The C compiler identification is MSVC 19.0.24225.1
-- The CXX compiler identification is MSVC 19.0.24225.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/Users/siege/Anaconda3/envs/caffe/Library/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/siege/Desktop/Novelsense/caffe-master/build/CMakeFiles/CMakeTmp

    Run Build Command:"C:/Users/siege/Anaconda3/envs/caffe/Library/bin/ninja.exe" "cmTC_46157"
    [1/2] Building C object CMakeFiles\cmTC_46157.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_46157.exe
    FAILED: cmTC_46157.exe
    cmd.exe /C "cd . && C:\Users\siege\Anaconda3\envs\caffe\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_46157.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_46157.dir\testCCompiler.c.obj  /out:cmTC_46157.exe /implib:cmTC_46157.lib /pdb:cmTC_46157.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_46157.dir/manifest.res CMakeFiles\cmTC_46157.dir/manifest.rc" failed (exit code 0) with the following output:
    Das System kann die angegebene Datei nicht finden
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:13 (project)


-- Configuring incomplete, errors occurred!
```

I am not too experienced with all the Build Tools, as i am a dumb Windows user 😄

**Comment by Franzisdrak** [comment]
@willyd Ok i will try this path tomorrow. Maybe even this evening. I decided to clean my whole system. I even broke my VS2017 installation during trying to fix it... This might have been the root cause.

**Comment by Franzisdrak** [comment]
@willyd I think i understand where the problem is. I have to tell python a path to the C++ libs. Do i just use the caffe-master? Do i need to build it, or just add the PATH?

**Comment by Franzisdrak** [comment]
There might be an error with the repo:
conda install caffe -c willyd
Solving environment: done

## Package Plan ##

  environment location: C:\Users\siege\Anaconda3\envs\caffe

  added / updated specs:
    - caffe


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tk-8.6.8                   |       hfa6e2cd_0         3.8 MB  anaconda
    libtiff-4.0.9              |       h36446d0_2         829 KB  anaconda
    zeromq-4.2.5               |       he025d50_1         9.5 MB  anaconda
    sqlite-3.25.2              |       hfa6e2cd_0         939 KB  anaconda
    boost-cpp-1.65.1           |       hfa6e2cd_4           4 KB  anaconda
    libpng-1.6.35              |       h2a8f88b_0         589 KB  anaconda
    libsodium-1.0.16           |       h9d3ae62_0         585 KB  anaconda
    ------------------------------------------------------------
                                           Total:        16.2 MB

The following NEW packages will be INSTALLED:

    caffe:     1.0-py37he774522_0 willyd

The following packages will be UPDATED:

    hdf5:      1.8.20-vc14_1      conda-forge [vc14] --> 1.8.20-hac2f561_1     anaconda
    icu:       58.2-vc14_0        conda-forge [vc14] --> 58.2-ha66f8fd_1       anaconda
    libpng:    1.6.34-vc14_0      conda-forge [vc14] --> 1.6.35-h2a8f88b_0     anaconda
    libsodium: 1.0.16-vc14_0      conda-forge [vc14] --> 1.0.16-h9d3ae62_0     anaconda
    libtiff:   4.0.9-vc14_0       conda-forge [vc14] --> 4.0.9-h36446d0_2      anaconda
    lmdb:      0.9.18-vc14_2      willyd      [vc14] --> 0.9.22-h6538335_1     anaconda
    qt:        5.6.2-vc14_1       conda-forge [vc14] --> 5.6.2-vc14h6f8c307_12 anaconda
    sqlite:    3.22.0-vc14_0      conda-forge [vc14] --> 3.25.2-hfa6e2cd_0     anaconda
    tk:        8.6.8-vc14_0       conda-forge [vc14] --> 8.6.8-hfa6e2cd_0      anaconda
    vc:        14-h0510ff6_3      anaconda    --> 14.1-h0510ff6_4       anaconda

The following packages will be DOWNGRADED:

    boost-cpp: 1.67.0-vc14_0      conda-forge [vc14] --> 1.65.1-hfa6e2cd_4     anaconda
    zeromq:    4.2.5-vc14_2       conda-forge [vc14] --> 4.2.5-he025d50_1      anaconda

Proceed ([y]/n)? y


Downloading and Extracting Packages
tk-8.6.8             | 3.8 MB    | ######################################################################### | 100%
libtiff-4.0.9        | 829 KB    | ######################################################################### | 100%
zeromq-4.2.5         | 9.5 MB    | ######################################################################### | 100%
sqlite-3.25.2        | 939 KB    | ######################################################################### | 100%
boost-cpp-1.65.1     | 4 KB      | ######################################################################### | 100%
libpng-1.6.35        | 589 KB    | ######################################################################### | 100%
libsodium-1.0.16     | 585 KB    | ######################################################################### | 100%
Preparing transaction: done
Verifying transaction: \
SafetyError: The package for caffe located at C:\Users\siege\Anaconda3\pkgs\caffe-1.0-py37he774522_0
appears to be corrupted. The path 'Lib/site-packages/caffe/draw.py'
has a sha256 mismatch.
  reported sha256: 583170dd624f6357c929ec115e9c8378dcd750a394f5bb6a87e58f8bdca1335a
  actual sha256: 6e95f93a7c2002ec973d6bd7886e14cdf08500ea809b246d6f29ae90ad7a9fa0

**Comment by Franzisdrak** [comment]
@willyd 
I have troubles understanding what i actually need to do. As the simple installation in Anaconda doesn't seem to work for me.

As far as i understand it, i need to:
1. Install the python packages in anaconda
```
conda create -n caffe python=3.7
conda activate caffe
conda config --add channels anaconda
conda install caffe -c willyd
```
This works, but throws the mentioned error one post above when importing caffe. Therefore it seems i need to build the binaries myself. ->

2. Build the C++ Binaries from the windows caffe tree.
I am following these instructions:
https://github.com/BVLC/caffe/tree/windows#using-the-python-interface
But i get this error: 
```
INFO: ============================================================
INFO: Summary:
INFO: ============================================================
INFO: MSVC_VERSION               = 15 (Changed location in the build_win.cmd)
INFO: WITH_NINJA                 = 1
INFO: CMAKE_GENERATOR            = "Ninja"
INFO: CPU_ONLY                   = 0
INFO: CUDA_ARCH_NAME             = Auto
INFO: CMAKE_CONFIG               = Release
INFO: USE_NCCL                   = 0
INFO: CMAKE_BUILD_SHARED_LIBS    = 0
INFO: PYTHON_VERSION             = 3
INFO: BUILD_PYTHON               = 1
INFO: BUILD_PYTHON_LAYER         = 1
INFO: BUILD_MATLAB               = 0
INFO: PYTHON_EXE                 = "python"
INFO: RUN_TESTS                  = 0
INFO: RUN_LINT                   = 0
INFO: RUN_INSTALL                = 0
INFO: ============================================================
Der Befehl ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\vcvarsall.bat"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
CMake Error at cmake/WindowsDownloadPrebuiltDependencies.cmake:40 (message):
  Could not find url for MSVC version = 1915 and Python version = 3.7.
```
Which makes sense as i can't seem to find any use of VS2017/py37 compiling on windows.
So would i just need to switch to VS2015?

3. Link to the Caffe.dlls where the C++ binaries lie.
https://github.com/BVLC/caffe/issues/5053

4. Start using Caffe

I hope you get my problem, if you need more info i am eager to help.

**Comment by sandeshshrestha45** [comment]
@willyd 
I successfully installed caffe without gpu in anaconda a following your instructions. But i cannot import it. I get the following error:

from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer File "C:\Users\San\Anaconda3\envs\caffe\lib\site-packages\caffe\pycaffe.py", line 13, in <module> from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \ ImportError: DLL load failed: The specified module could not be found.

![1](https://user-images.githubusercontent.com/10694553/51452594-be213980-1d6d-11e9-8c7a-c070ab1b8be0.JPG)


Could you please help me with this?

**Comment by bth5032** [comment]
I'm having the same error on Windows after installing caffe-cpu with anaconda using the following:

```
conda config --add channels anaconda
conda install caffe-cpu -c willyd
```

```(base) ... >python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bobakh\AppData\Local\Continuum\anaconda3\lib\site-packages\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "C:\Users\bobakh\AppData\Local\Continuum\anaconda3\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: DLL load failed: The specified module could not be found.
>>>```

**Comment by zwbzwj123** [comment]
@bth5032
I sovled this error by the following step:
1.  Download file.   
Link1:  https://pan.baidu.com/s/1gsNue1PLq8I2ShNTmuTQAQ     password:  im73
Link2:  https://drive.google.com/open?id=1my1UZDZaii9AtDExRRPDTHQFM9Nj8smG
2.  Decompression the file you download and replaces the folder ..\Anaconda3\envs\caffe\Lib\site-packages\caffe

**Comment by Banus** [comment]
With `caffe-cpu` I have the same problem of 'DLL load failed', under Windows 10 and conda Python 3.7.

Launching the `caffe` command from terminal, some debug DLLs are missing, e.g. `UCRTBASED` or `VCRUNTIME14D`. Dependency walker seems to suggest that the problem is in `GLOG.DLL`.

![image](https://user-images.githubusercontent.com/903651/57680091-1cc83700-762d-11e9-8703-1d68e14eae41.png)

Unfortunately Caffe depends on this specific version, and trying to force a different one leads to the removal of the `caffe-cpu` package, so I wasn't able to verify if this is the source of the problem.

**Comment by WMF1997** [comment]
Hello @willyd :

I installed caffe and caffe-cpu via your conda packages successfully. And I want to ask a little question. 

If I use a new **C++ layer**(NOT PYTHON LAYER) which is not in the origin caffe layers. for example, i use a triplet loss layer, the link of the triplet loss is [here](https://github.com/seuliufeng/DeepSBIR/blob/master/caffe_sbir/src/caffe/layers/triplet_loss_layer.cpp).
And I want to use this layer in a project. what should I do if I want to use this new C++/CUDA layer? (Is it right to put the .hpp, .cpp, .cu files to their related folders, and then just run the python code? (P.S. I use pycaffe))

yours, 
@WMF1997

**Comment by willyd** [comment]
@WMF1997

Short answer: you can't.

Long answer: What you suggest is the right way to do it though. But you need to rebuild the conda packages by yourself. It could be as simple as:

1. Copy the files of the triplet loss layer as you suggest
2. Checkout this branch https://github.com/willyd/caffe/tree/windows
3. `conda install conda-build`
4. `cd caffe\\conda && conda build .`

I am not sure this will work since the conda recipes found in this branch might be out of date. I really don't have much time to dedicate to the caffe project these days. Otherwise, try to follow the standard building from source procedure.

**Comment by WMF1997** [comment]
Thank you very much~ @willyd

**Comment by HuangShiqing** [comment]
btw，if you just want to install a caffe-cpu on windows, It could be as simple as:
//I have try python27 and 35, all failed, only 36 succeed
conda create -n caffe36 python=3.6
conda activate caffe36
conda install -c willyd caffe-cpu

**Comment by lazylazypig** [comment]
@bth5032 Hi, have you sloved the 'import caffe' problem?

**Comment by bth5032** [comment]
@lazylazypig nope, switched to pytorch 😅

**Comment by sgnet91** [comment]
Hi @willyd ,
After having tried many solutions without success, I've tried your procedure but I'm still not able to import caffe.
![image](https://user-images.githubusercontent.com/60738202/75037131-bfaebb00-54b3-11ea-9782-bbdd93e48575.png)
![image](https://user-images.githubusercontent.com/60738202/75037183-db19c600-54b3-11ea-9bcf-841a03da490c.png)
![image](https://user-images.githubusercontent.com/60738202/75037218-ee2c9600-54b3-11ea-8ae2-7f5b6bd5ba6b.png)
![image](https://user-images.githubusercontent.com/60738202/75037242-ff75a280-54b3-11ea-8e3b-7f5bb04c4d4f.png)
![image](https://user-images.githubusercontent.com/60738202/75037308-29c76000-54b4-11ea-992f-f5334a9cb60d.png)

**Comment by Kings77** [comment]
Hi @willyd i tried using the method that you suggest but i faced some problems. i installed it using the anaconda promp since im using the anaconda3. when i installed, it become an envs folder and not as the pkg. so i cant import caffe inside my work envs. what should i do?

> I have published conda packages. Please install with these commands:
> 
> ```batchfile
> REM Create a new conda environment to install Caffe
> REM You can use python 3.5, 3.6 or 3.7
> conda create -n caffe python=3.7
> REM activate the environment
> REM Depending on your conda version you may have to use activate caffe
> conda activate caffe
> REM add the anaconda channel to resolve all dependencies
> conda config --add channels anaconda
> REM Install caffe with cuda support or install caffe-cpu if you do not want CUDA support
> conda install caffe -c willyd
> ```
> 
> Currently only CUDA 9.0 is built but I will merge the files to build the packages once I have confirmation that the packages work.

**Comment by Alabenba** [comment]
> @willyd
> I successfully installed caffe without gpu in anaconda a following your instructions. But i cannot import it. I get the following error:
> from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer File "C:\Users\San\Anaconda3\envs\caffe\lib\site-packages\caffe\pycaffe.py", line 13, in  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \ ImportError: DLL load failed: The specified module could not be found.
> 
> Could you please help me with this?

I have the same problem. Have you fixed it?

**Comment by sgnet91** [comment]
No, unfortunately not. I gave up the idea of using caffe and switched to keras. Good luck!

**Comment by liaojimzen** [comment]
So there is any idea to instead caffe?

**Comment by husamhamu** [comment]
> I have published conda packages. Please install with these commands:
> 
> ```batchfile
> REM Create a new conda environment to install Caffe
> REM You can use python 3.5, 3.6 or 3.7
> conda create -n caffe python=3.7
> REM activate the environment
> REM Depending on your conda version you may have to use activate caffe
> conda activate caffe
> REM add the anaconda channel to resolve all dependencies
> conda config --add channels anaconda
> REM Install caffe with cuda support or install caffe-cpu if you do not want CUDA support
> conda install caffe -c willyd
> ```
> 
> Currently only CUDA 9.0 is built but I will merge the files to build the packages once I have confirmation that the packages work.

That didn't work for me. I am getting an error when I try to import caffe:
```
`Traceback (most recent call last):
  File "project_path", line 1, in <module>
    from DetectAndTrack import *
  File "project_path", line 2, in <module>
    from goturn.network.regressor import regressor
  File "project_path", line 10, in <module>
    import caffe
  File "..3\anaconda\envs\caffe\lib\site-packages\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "..\anaconda\envs\caffe\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \ 
ImportError: DLL load failed: The specified module could not be found.`
```

**Comment by AydinAlptug** [comment]
any update on this issue?

**Comment by ayushrox** [comment]
same problem, can anyone please answer?

**Comment by hattaaldino** [comment]
> Thank you very much~ @willyd

Hi @WMF1997, have you managed to do the solution by @willyd
