### ISSUE TITLE
no module named caffe

### ISSUE THREAD

**Issue by bwanaaa** [BVLC/caffe#6733]
caffe and pycaffe were built properly and passed all tests
(I used this script
https://gist.github.com/ewnd9/3d3f688f8c6d3fe643f1)

I moved caffe directory to my home directory 
caffe directory contains python directory which also contains caffe directory in which is _caffe.so

issuing
`$sudo find / -name '_caffe.so'`
gives
```
/home/stefan/caffe/python/caffe/_caffe.so
/home/stefan/caffe/build/lib/_caffe.so

```

.profile contains
```
PYTHONPATH=/home/stefan/caffe/python:$PYTHONPATH
PYTHONPATH=/usr/local${PYTHONPATH:+:${PYTHONPATH}}
LD_LIBRARY_PATH=/usr/local/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

```
echo $PYTHONPATH gives

`/usr/local:/home/stefan/caffe/python:`

opening a python prompt allows these commands
```
>>>import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffe

>>>import sys
>>>sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']

>>>sys.path.append(home/stefan/caffe/python)
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffe

>>> sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', 'home/stefan/caffe/python']
>>> 

### System configuration

ubuntu 18.02LTS
gcc 7.3.0
CUDA 10.1
CUDNN_MAJOR 7
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    include_dirs = ['/usr/local/include', '/usr/include']

python 2.7.13

Recommended next step?

**Comment by bwanaaa** [comment]
pycaffe did not compile properly. once compiled and the library was not in RED, problem solved.
