### ISSUE TITLE
Problem while importing caffe in Python

### ISSUE THREAD

**Issue by sayanghosh** [BVLC/caffe#703]
When I try to import caffe from the terminal in Ubuntu by the command python -c "import caffe", I get the following error :

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sghosh/mnt/Sayancode/caffe/caffe/distribute/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/sghosh/mnt/Sayancode/caffe/caffe/distribute/python/caffe/pycaffe.py", line 10, in <module>
    from ._caffe import Net, SGDSolver
ImportError: /home/sghosh/anaconda/bin/../lib/libm.so.6: version `GLIBC_2.15' not found (required by /usr/lib/x86_64-linux-gnu/libvorbis.so.0)
```

Could anyone assist here ?

**Comment by dvreed77** [comment]
I am getting this error as well, but can't seem to figure out how to solve it.  Doing a `locate libm.so.6` I see this:

    /home/dreed/anaconda/lib/libm.so.6
    /home/dreed/anaconda/pkgs/system-5.8-1/lib/libm.so.6
    /lib/x86_64-linux-gnu/libm.so.6

Isn't this correct?
