### ISSUE TITLE
IMPORT ERROR

### ISSUE THREAD

**Issue by DongStop** [BVLC/caffe#7048]
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import caffe  
  File "/home/dong/work/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/dong/work/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/dong/work/caffe/build/lib/libcaffe.so.1.0.0: unexpected reloc type 0x03

**Comment by xiaolin1990** [comment]
这是来自QQ邮箱的假期自动回复邮件。 谢谢，您的邮件已收到，尽快给您回复。

**Comment by lovie123** [comment]
您好，邮件已收到，谢谢！

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Rocksnake** [comment]
> Traceback (most recent call last): File "demo.py", line 6, in import caffe File "/home/dong/work/caffe/python/caffe/**init**.py", line 1, in from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer File "/home/dong/work/caffe/python/caffe/pycaffe.py", line 13, in from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, ImportError: /home/dong/work/caffe/build/lib/libcaffe.so.1.0.0: unexpected reloc type 0x03

@DongStop The reason for this problem is that the relevant dependencies are missing in your python compilation environment.
You only need to download the relevant dependencies through `pip` or `conda`
just like:
`pip install <source-package>`
`conda install <source-package>`

**Comment by DongStop** [comment]
> 

But I dont't know what dependencies are missing.the compiling process is successful.

**Comment by DongStop** [comment]
@Rocksnake But I dont't know what dependencies are missing.the compiling process is successful.

**Comment by DongStop** [comment]
@Rocksnake the cmake information as follow
 ******************* Caffe Configuration Summary *******************
General:
Version           :   1.0.0
Git               :   1.0-136-g9b891540-dirty
System            :   Linux
C++ compiler      :   /usr/bin/c++
Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
Build type        :   Release 
BUILD_SHARED_LIBS :   ON
BUILD_python      :   ON
BUILD_matlab      :   OFF
BUILD_docs        :   ON
CPU_ONLY          :   ON
USE_OPENCV        :   ON
USE_LEVELDB       :   ON
USE_LMDB          :   ON
USE_NCCL          :   OFF
ALLOW_LMDB_NOLOCK :   OFF
USE_HDF5          :   ON 
Dependencies:
BLAS              :   Yes (Atlas)
Boost             :   Yes (ver. 1.78)
glog              :   Yes
gflags            :   Yes
protobuf          :   Yes (ver. ..)
lmdb              :   Yes (ver. 0.9.24)
LevelDB           :   Yes (ver. 1.22)
Snappy            :   Yes (ver. 1.1.8)
OpenCV            :   Yes (ver. 3.4.16)
CUDA              :   No 
Python:
Interpreter       :   /usr/bin/python (ver. 3.7.1)
Libraries         :   /usr/local/lib/libpython3.7m.a (ver 3.7.1)
NumPy             :   /usr/local/lib/python3.7/site-packages/numpy/core/include (ver 1.21.5)
 
Documentaion:
Doxygen           :   No
config_file       :    
Install:
Install path      :   /home/dong/work/caffe/build/install
Configuring done
Generating done
Build files have been written to: /home/dong/work/caffe/build

**Comment by Rocksnake** [comment]
The package after the from keyword is a large package, and the package after the import keyword is included in the former.
You can choose to download the package after the from keyword, or you can choose to download the package after the import.
I think you just need to execute these code:
`pip install caffe`
`pip install .pycaffe`
`pip install ._caffe`

**Comment by DongStop** [comment]
@Rocksnake  my hardware doesn't support GPU.maybe using pip to install doesn't make it work!

**Comment by DongStop** [comment]
![image](https://user-images.githubusercontent.com/66958826/156698078-289be7d0-4be0-4250-afa4-5859f2610699.png)
