### ISSUE TITLE
'GDK_IS_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by xizhonghua** [BVLC/caffe#861]
I was not able to run classify.py via SSH.
I don't want to use X11 during classification, is there any way to avoid that?

zxi@pearl:~/repo/CNN/scripts$ ./classify.py 12.png out

(classify.py:28845): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "./classify.py", line 14, in <module>
    import caffe
  File "/home/zxi/repo/CNN/scripts/caffe/**init**.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/zxi/repo/CNN/scripts/caffe/pycaffe.py", line 11, in <module>
    import caffe.io
  File "/home/zxi/repo/CNN/scripts/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/**init**.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 91, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 71, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 83, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 253, in use_plugin
    _load(name)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 297, in _load
    fromlist=[modname])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 98, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 28, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 7, in <module>
    import backend_gtk3
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py", line 49, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

**Comment by jashmenn** [comment]
For me it seems to be `matplotlib` that causes this. If you want to run totally headless at the top of your script you can also try: 

```
import matplotlib 
matplotlib.use('Agg') 
```

Which will tell `matplotlib` not to try to load up GTK.

**Comment by mahrens917** [comment]
Thanks @jashmenn - your solution works perfectly.

**Comment by sebastianffx** [comment]
Thanks @jashmenn !
Now it works +1

**Comment by Saneesh** [comment]
Now I could login through ssh and my issue is solved!
These are the steps I have followed
username@local:~# sudo -s
root@local:~# ssh -X -v -i /home/username/Downloads/keypair.pem ubuntu@ec2-xx-xx-xx-xx.compute-x.amazonaws.com
ubuntu@amazon:~# sudo -s
root@amazon:~# nohup ./digits-devserver &

Now, access the site and create the dataset!

**Comment by axeltidemann** [comment]
In similar spirit to @jashmenn, it is possible to specify this at runtime or set an environment variable:
`MPLBACKEND=Agg python your_script.py`

**Comment by LaurenLuoYun** [comment]
sudo pip uninstall matplotlib 
sudo apt-get install python-matplotlib

use python-matplotlib can solve the problom.

**Comment by sjaramillo10** [comment]
I was having that problem on my Raspberry Pi and using what @LaurenLuoYun said solved my problem.
Thank you!

**Comment by unifiDa** [comment]
I had the same problem, and to me the solution was:
 env MPLBACKEND=Agg python testing.py ...

**Comment by lifematrix** [comment]
@unifiDa It is a nice solution. Thanks!

**Comment by ssrzz** [comment]
> tell `matplotlib` not to try to load up GTK.

Solved my problems. Thanks @jashmenn

**Comment by mikechen66** [comment]
Solution to 'GDK_IS_DISPLAY (display)' failed

It seems that the error is a minor error during the ssh connection from a computer to another computer. While I run the test application of class_activation_maps.py (keras examples), it shows the same error.

$ python3 class_activation_maps.py /home/nvidia/Downloads/galaxy.jpg
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(image_ocr.py:1257): Gdk-CRITICAL **: 19:44:35.690: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

Using TensorFlow backend.
.........

However, while I run the following both the commands and the application. It can successfully show the splendid galaxy makeup.

$ echo $DISPLAY
:0
$ python3 class_activation_maps.py /home/nvidia/Downloads/galaxy.jpg

Using TensorFlow backend.
2020-05-01 19:45:14.877288: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0

Notes:

Another solution is to describe the above-metioned commands in bashrc.

Cheers,

Mike
